apiVersion: v1
kind: Service
metadata:
  name: unikube-postgres
  labels:
    service: unikube
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 31893
  selector:
    service: unikube
    app: postgres
